[2025-07-13T16:52:52.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:52:52.891+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model manual__2025-07-13T16:36:30+00:00 [queued]>
[2025-07-13T16:52:52.904+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model manual__2025-07-13T16:36:30+00:00 [queued]>
[2025-07-13T16:52:52.905+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 5
[2025-07-13T16:52:52.924+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-13 16:36:30+00:00
[2025-07-13T16:52:52.935+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=422) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T16:52:52.937+0000] {standard_task_runner.py:72} INFO - Started process 428 to run task
[2025-07-13T16:52:52.936+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'manual__2025-07-13T16:36:30+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpljexkqq_']
[2025-07-13T16:52:52.939+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask tune_model
[2025-07-13T16:52:52.960+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T16:52:53.016+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model manual__2025-07-13T16:36:30+00:00 [running]> on host 6011aa489c7f
[2025-07-13T16:52:53.129+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:36:30+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:36:30+00:00'
[2025-07-13T16:52:53.131+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:52:53.151+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T16:52:53.153+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --features_table turnstile_features         ']
[2025-07-13T16:52:53.176+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T16:52:59.342+0000] {subprocess.py:106} INFO - Train shape: (0, 8)
[2025-07-13T16:52:59.343+0000] {subprocess.py:106} INFO - Validation shape: (0, 8)
[2025-07-13T16:52:59.343+0000] {subprocess.py:106} INFO - Max datetime in dataset: NaT
[2025-07-13T16:52:59.468+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]2025/07/13 16:52:59 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-07-13T16:52:59.469+0000] {subprocess.py:106} INFO - The git executable must be specified in one of the following ways:
[2025-07-13T16:52:59.471+0000] {subprocess.py:106} INFO -     - be included in your $PATH
[2025-07-13T16:52:59.472+0000] {subprocess.py:106} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-07-13T16:52:59.473+0000] {subprocess.py:106} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-07-13T16:52:59.473+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.474+0000] {subprocess.py:106} INFO - All git commands will error until this is rectified.
[2025-07-13T16:52:59.475+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.476+0000] {subprocess.py:106} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-07-13T16:52:59.477+0000] {subprocess.py:106} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-07-13T16:52:59.478+0000] {subprocess.py:106} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-07-13T16:52:59.479+0000] {subprocess.py:106} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-07-13T16:52:59.480+0000] {subprocess.py:106} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-07-13T16:52:59.481+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.481+0000] {subprocess.py:106} INFO - Example:
[2025-07-13T16:52:59.483+0000] {subprocess.py:106} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-07-13T16:52:59.484+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.486+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.750+0000] {subprocess.py:106} INFO -                                                       [16:52:59] WARNING: ../src/learner.cc:767:
[2025-07-13T16:52:59.751+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T16:52:59.753+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:52:59.754+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:52:59.755+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:52:59.874+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:52:59.880+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:52:59.976+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:52:59.977+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:52:59] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.065+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.075+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.168+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.170+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.298+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.300+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.380+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.382+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.489+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.490+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.593+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.594+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.673+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.674+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.783+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      [16:53:00] WARNING: ../src/learner.cc:1517: Empty dataset at worker: 0
[2025-07-13T16:53:00.864+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      🏃 View run tune-20250713-165259 at: http://mlflow:5000/#/experiments/1/runs/7343de954a174f72a76515c8cc285aa8
[2025-07-13T16:53:00.866+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:53:00.867+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T16:53:00.868+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:53:00.939+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]job exception: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
[2025-07-13T16:53:00.940+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:53:00.941+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]
[2025-07-13T16:53:00.942+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T16:53:00.942+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 122, in <module>
[2025-07-13T16:53:00.946+0000] {subprocess.py:106} INFO -     tune(df, args.experiment_name, args.run_prefix, args.n_trials)
[2025-07-13T16:53:00.947+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 81, in tune
[2025-07-13T16:53:00.953+0000] {subprocess.py:106} INFO -     best_result = fmin(
[2025-07-13T16:53:00.954+0000] {subprocess.py:106} INFO -                   ^^^^^
[2025-07-13T16:53:00.955+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 540, in fmin
[2025-07-13T16:53:00.956+0000] {subprocess.py:106} INFO -     return trials.fmin(
[2025-07-13T16:53:00.956+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-07-13T16:53:00.957+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/base.py", line 671, in fmin
[2025-07-13T16:53:00.958+0000] {subprocess.py:106} INFO -     return fmin(
[2025-07-13T16:53:00.958+0000] {subprocess.py:106} INFO -            ^^^^^
[2025-07-13T16:53:00.959+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 586, in fmin
[2025-07-13T16:53:00.960+0000] {subprocess.py:106} INFO -     rval.exhaust()
[2025-07-13T16:53:00.960+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 364, in exhaust
[2025-07-13T16:53:00.961+0000] {subprocess.py:106} INFO -     self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
[2025-07-13T16:53:00.962+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 300, in run
[2025-07-13T16:53:00.963+0000] {subprocess.py:106} INFO -     self.serial_evaluate()
[2025-07-13T16:53:00.964+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
[2025-07-13T16:53:00.965+0000] {subprocess.py:106} INFO -     result = self.domain.evaluate(spec, ctrl)
[2025-07-13T16:53:00.967+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.968+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/base.py", line 892, in evaluate
[2025-07-13T16:53:00.969+0000] {subprocess.py:106} INFO -     rval = self.fn(pyll_rval)
[2025-07-13T16:53:00.970+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.971+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 73, in objective
[2025-07-13T16:53:00.983+0000] {subprocess.py:106} INFO -     rmse = root_mean_squared_error(y_val, y_pred)
[2025-07-13T16:53:00.984+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.985+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
[2025-07-13T16:53:00.986+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-07-13T16:53:00.987+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.987+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 665, in root_mean_squared_error
[2025-07-13T16:53:00.988+0000] {subprocess.py:106} INFO -     mean_squared_error(
[2025-07-13T16:53:00.989+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 191, in wrapper
[2025-07-13T16:53:00.989+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-07-13T16:53:00.990+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.991+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 580, in mean_squared_error
[2025-07-13T16:53:00.992+0000] {subprocess.py:106} INFO -     _check_reg_targets_with_floating_dtype(
[2025-07-13T16:53:00.992+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 209, in _check_reg_targets_with_floating_dtype
[2025-07-13T16:53:00.993+0000] {subprocess.py:106} INFO -     y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
[2025-07-13T16:53:00.994+0000] {subprocess.py:106} INFO -                                                          ^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:00.995+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 115, in _check_reg_targets
[2025-07-13T16:53:00.996+0000] {subprocess.py:106} INFO -     y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
[2025-07-13T16:53:00.998+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:53:01.000+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1128, in check_array
[2025-07-13T16:53:01.001+0000] {subprocess.py:106} INFO -     raise ValueError(
[2025-07-13T16:53:01.002+0000] {subprocess.py:106} INFO - ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
[2025-07-13T16:53:01.671+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T16:53:01.690+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:53:01.700+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=manual__2025-07-13T16:36:30+00:00, execution_date=20250713T163630, start_date=20250713T165252, end_date=20250713T165301
[2025-07-13T16:53:01.746+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:53:01.749+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 428)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:53:01.763+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T16:53:01.801+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:53:01.807+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
