[2025-07-16T14:48:30.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T14:48:30.842+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T14:48:30.861+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T14:48:30.862+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-16T14:48:30.884+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_monitoring> on 2025-07-15 00:00:00+00:00
[2025-07-16T14:48:30.899+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T14:48:30.901+0000] {standard_task_runner.py:72} INFO - Started process 3203 to run task
[2025-07-16T14:48:30.900+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'run_monitoring', 'scheduled__2025-07-15T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp5ct67fp1']
[2025-07-16T14:48:30.904+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask run_monitoring
[2025-07-16T14:48:30.925+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T14:48:30.992+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [running]> on host d84888688479
[2025-07-16T14:48:30.994+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T14:48:31.115+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='run_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T00:00:00+00:00'
[2025-07-16T14:48:31.117+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T14:48:31.142+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-16T14:48:31.143+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/monitor.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --predictions_table predictions                 --monitoring_table monitoring\n        ']
[2025-07-16T14:48:31.169+0000] {subprocess.py:99} INFO - Output:
[2025-07-16T14:48:33.795+0000] {subprocess.py:106} INFO - /opt/***/pipeline/monitor.py:59: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
[2025-07-16T14:48:33.796+0000] {subprocess.py:106} INFO -   target_date = (datetime.utcnow() - timedelta(days=1)).date()
[2025-07-16T14:48:34.753+0000] {subprocess.py:106} INFO - [Monitoring] For date: 2025-07-15
[2025-07-16T14:48:34.753+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-16T14:48:34.754+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 107, in <module>
[2025-07-16T14:48:34.757+0000] {subprocess.py:106} INFO -     run_monitoring(
[2025-07-16T14:48:34.758+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 63, in run_monitoring
[2025-07-16T14:48:34.761+0000] {subprocess.py:106} INFO -     df_actual = fetch_actual_data(str(target_date))
[2025-07-16T14:48:34.762+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-16T14:48:34.763+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 15, in fetch_actual_data
[2025-07-16T14:48:34.768+0000] {subprocess.py:106} INFO -     df["date"] = pd.to_datetime(df["date"])
[2025-07-16T14:48:34.769+0000] {subprocess.py:106} INFO -                                 ~~^^^^^^^^
[2025-07-16T14:48:34.769+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
[2025-07-16T14:48:34.770+0000] {subprocess.py:106} INFO -     indexer = self.columns.get_loc(key)
[2025-07-16T14:48:34.771+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-16T14:48:34.772+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
[2025-07-16T14:48:34.774+0000] {subprocess.py:106} INFO -     raise KeyError(key)
[2025-07-16T14:48:34.775+0000] {subprocess.py:106} INFO - KeyError: 'date'
[2025-07-16T14:48:34.988+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-16T14:48:35.006+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T14:48:35.015+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=run_monitoring, run_id=scheduled__2025-07-15T00:00:00+00:00, execution_date=20250715T000000, start_date=20250716T144830, end_date=20250716T144835
[2025-07-16T14:48:35.062+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T14:48:35.063+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task run_monitoring (Bash command failed. The command returned a non-zero exit code 1.; 3203)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T14:48:35.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-16T14:48:35.123+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T14:48:35.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-16T18:50:06.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T18:50:06.183+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T18:50:06.201+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T18:50:06.202+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-16T18:50:06.228+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_monitoring> on 2025-07-15 00:00:00+00:00
[2025-07-16T18:50:06.241+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T18:50:06.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'run_monitoring', 'scheduled__2025-07-15T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmppo3qr9hw']
[2025-07-16T18:50:06.244+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask run_monitoring
[2025-07-16T18:50:06.244+0000] {standard_task_runner.py:72} INFO - Started process 496 to run task
[2025-07-16T18:50:06.265+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T18:50:06.330+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [running]> on host 36b6cbfeb7c6
[2025-07-16T18:50:06.335+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T18:50:06.470+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='run_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T00:00:00+00:00'
[2025-07-16T18:50:06.472+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T18:50:06.503+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-16T18:50:06.504+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/monitor.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --predictions_table predictions                 --monitoring_table monitoring\n        ']
[2025-07-16T18:50:06.525+0000] {subprocess.py:99} INFO - Output:
[2025-07-16T18:50:08.727+0000] {subprocess.py:106} INFO - /opt/***/pipeline/monitor.py:59: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
[2025-07-16T18:50:08.728+0000] {subprocess.py:106} INFO -   target_date = (datetime.utcnow() - timedelta(days=1)).date()
[2025-07-16T18:50:09.687+0000] {subprocess.py:106} INFO - [Monitoring] For date: 2025-07-15
[2025-07-16T18:50:09.688+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-16T18:50:09.689+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 107, in <module>
[2025-07-16T18:50:09.692+0000] {subprocess.py:106} INFO -     run_monitoring(
[2025-07-16T18:50:09.693+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 63, in run_monitoring
[2025-07-16T18:50:09.696+0000] {subprocess.py:106} INFO -     df_actual = fetch_actual_data(str(target_date))
[2025-07-16T18:50:09.697+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-16T18:50:09.698+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 15, in fetch_actual_data
[2025-07-16T18:50:09.699+0000] {subprocess.py:106} INFO -     df["date"] = pd.to_datetime(df["date"])
[2025-07-16T18:50:09.700+0000] {subprocess.py:106} INFO -                                 ~~^^^^^^^^
[2025-07-16T18:50:09.700+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
[2025-07-16T18:50:09.703+0000] {subprocess.py:106} INFO -     indexer = self.columns.get_loc(key)
[2025-07-16T18:50:09.704+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-16T18:50:09.706+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
[2025-07-16T18:50:09.707+0000] {subprocess.py:106} INFO -     raise KeyError(key)
[2025-07-16T18:50:09.708+0000] {subprocess.py:106} INFO - KeyError: 'date'
[2025-07-16T18:50:09.899+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-16T18:50:09.916+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T18:50:09.927+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=run_monitoring, run_id=scheduled__2025-07-15T00:00:00+00:00, execution_date=20250715T000000, start_date=20250716T185006, end_date=20250716T185009
[2025-07-16T18:50:09.974+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T18:50:09.975+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task run_monitoring (Bash command failed. The command returned a non-zero exit code 1.; 496)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T18:50:10.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-16T18:50:10.028+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T18:50:10.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-16T19:17:15.859+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T19:17:15.907+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T19:17:15.929+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T19:17:15.930+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-16T19:17:15.954+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_monitoring> on 2025-07-15 00:00:00+00:00
[2025-07-16T19:17:15.970+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T19:17:15.970+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'run_monitoring', 'scheduled__2025-07-15T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpf0c21o4o']
[2025-07-16T19:17:15.973+0000] {standard_task_runner.py:72} INFO - Started process 291 to run task
[2025-07-16T19:17:15.974+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask run_monitoring
[2025-07-16T19:17:16.003+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T19:17:16.082+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.run_monitoring scheduled__2025-07-15T00:00:00+00:00 [running]> on host e42e59698f90
[2025-07-16T19:17:16.086+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T19:17:16.235+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='run_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T00:00:00+00:00'
[2025-07-16T19:17:16.237+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T19:17:16.296+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-16T19:17:16.298+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/monitor.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --predictions_table predictions                 --monitoring_table monitoring                 --reference_date 2022-07-16\n        ']
[2025-07-16T19:17:16.322+0000] {subprocess.py:99} INFO - Output:
[2025-07-16T19:17:19.642+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-16T19:17:19.643+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 109, in <module>
[2025-07-16T19:17:19.647+0000] {subprocess.py:106} INFO -     run_monitoring(
[2025-07-16T19:17:19.649+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/monitor.py", line 61, in run_monitoring
[2025-07-16T19:17:19.652+0000] {subprocess.py:106} INFO -     print(f"[Monitoring] For date: {target_date}")
[2025-07-16T19:17:19.653+0000] {subprocess.py:106} INFO -                                     ^^^^^^^^^^^
[2025-07-16T19:17:19.654+0000] {subprocess.py:106} INFO - NameError: name 'target_date' is not defined
[2025-07-16T19:17:19.844+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-16T19:17:19.864+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T19:17:19.871+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=run_monitoring, run_id=scheduled__2025-07-15T00:00:00+00:00, execution_date=20250715T000000, start_date=20250716T191715, end_date=20250716T191719
[2025-07-16T19:17:19.914+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T19:17:19.915+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task run_monitoring (Bash command failed. The command returned a non-zero exit code 1.; 291)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-16T19:17:19.948+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-16T19:17:19.977+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T19:17:19.981+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
