[2025-07-20T15:51:23.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-20T15:51:23.565+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-20T15:50:12.719100+00:00 [queued]>
[2025-07-20T15:51:23.585+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-20T15:50:12.719100+00:00 [queued]>
[2025-07-20T15:51:23.586+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-07-20T15:51:23.619+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-07-20 15:50:12.719100+00:00
[2025-07-20T15:51:23.636+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3074) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-20T15:51:23.639+0000] {standard_task_runner.py:72} INFO - Started process 3080 to run task
[2025-07-20T15:51:23.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'manual__2025-07-20T15:50:12.719100+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpqm768txi']
[2025-07-20T15:51:23.642+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask download_and_ingest
[2025-07-20T15:51:23.667+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-20T15:51:23.725+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-20T15:50:12.719100+00:00 [running]> on host e42e59698f90
[2025-07-20T15:51:23.868+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='download_and_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T15:50:12.719100+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-20T15:50:12.719100+00:00'
[2025-07-20T15:51:23.869+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-20T15:51:23.901+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-20T15:51:23.903+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/download_ingest.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --table_name raw_turnstile_data\n        ']
[2025-07-20T15:51:23.921+0000] {subprocess.py:99} INFO - Output:
[2025-07-20T15:51:27.289+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-20T15:51:27.290+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 69, in <module>
[2025-07-20T15:51:27.295+0000] {subprocess.py:106} INFO -     download_and_ingest(year=year,
[2025-07-20T15:51:27.296+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 23, in download_and_ingest
[2025-07-20T15:51:27.300+0000] {subprocess.py:106} INFO -     for day in range(start_day, end_day + 1)
[2025-07-20T15:51:27.301+0000] {subprocess.py:106} INFO -                                 ~~~~~~~~^~~
[2025-07-20T15:51:27.302+0000] {subprocess.py:106} INFO - TypeError: can only concatenate tuple (not "int") to tuple
[2025-07-20T15:51:27.530+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-20T15:51:27.549+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-20T15:51:27.559+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, run_id=manual__2025-07-20T15:50:12.719100+00:00, execution_date=20250720T155012, start_date=20250720T155123, end_date=20250720T155127
[2025-07-20T15:51:27.618+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-20T15:51:27.626+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task download_and_ingest (Bash command failed. The command returned a non-zero exit code 1.; 3080)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-20T15:51:27.696+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-20T15:51:27.759+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-20T15:51:27.782+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
