[2025-08-02T16:28:09.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-02T16:28:09.933+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-08-02T16:28:02.032652+00:00 [queued]>
[2025-08-02T16:28:09.944+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-08-02T16:28:02.032652+00:00 [queued]>
[2025-08-02T16:28:09.945+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-02T16:28:09.964+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-08-02 16:28:02.032652+00:00
[2025-08-02T16:28:09.974+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-02T16:28:09.976+0000] {standard_task_runner.py:72} INFO - Started process 37 to run task
[2025-08-02T16:28:09.977+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'manual__2025-08-02T16:28:02.032652+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/turnstile_ml_pipeline.py', '--cfg-path', '/tmp/tmpkhaeyd3w']
[2025-08-02T16:28:09.980+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask download_and_ingest
[2025-08-02T16:28:10.003+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-02T16:28:10.064+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-08-02T16:28:02.032652+00:00 [running]> on host c251983940f5
[2025-08-02T16:28:10.202+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='download_and_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T16:28:02.032652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T16:28:02.032652+00:00'
[2025-08-02T16:28:10.205+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-02T16:28:10.273+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-02T16:28:10.275+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/download_ingest.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --table_name raw_turnstile_data\n        ']
[2025-08-02T16:28:10.290+0000] {subprocess.py:99} INFO - Output:
[2025-08-02T16:28:13.124+0000] {subprocess.py:106} INFO - 2025-08-02 16:28:13.123416+00:00
[2025-08-02T16:28:13.125+0000] {subprocess.py:106} INFO - [INFO] Fetching data for dates: []
[2025-08-02T16:28:13.126+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-08-02T16:28:13.127+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 70, in <module>
[2025-08-02T16:28:13.130+0000] {subprocess.py:106} INFO -     download_and_ingest(year=year,
[2025-08-02T16:28:13.131+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 28, in download_and_ingest
[2025-08-02T16:28:13.136+0000] {subprocess.py:106} INFO -     df_raw = pd.concat(dfs, ignore_index=True)
[2025-08-02T16:28:13.137+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T16:28:13.138+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
[2025-08-02T16:28:13.139+0000] {subprocess.py:106} INFO -     op = _Concatenator(
[2025-08-02T16:28:13.140+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^
[2025-08-02T16:28:13.141+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
[2025-08-02T16:28:13.142+0000] {subprocess.py:106} INFO -     objs, keys = self._clean_keys_and_objs(objs, keys)
[2025-08-02T16:28:13.143+0000] {subprocess.py:106} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T16:28:13.144+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
[2025-08-02T16:28:13.146+0000] {subprocess.py:106} INFO -     raise ValueError("No objects to concatenate")
[2025-08-02T16:28:13.148+0000] {subprocess.py:106} INFO - ValueError: No objects to concatenate
[2025-08-02T16:28:13.290+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-08-02T16:28:13.306+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T16:28:13.313+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, run_id=manual__2025-08-02T16:28:02.032652+00:00, execution_date=20250802T162802, start_date=20250802T162809, end_date=20250802T162813
[2025-08-02T16:28:13.352+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-02T16:28:13.353+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task download_and_ingest (Bash command failed. The command returned a non-zero exit code 1.; 37)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T16:28:13.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-02T16:28:13.411+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T16:28:13.419+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
