[2025-07-13T16:56:34.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:56:34.741+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.preprocess_train manual__2025-07-13T16:36:30+00:00 [queued]>
[2025-07-13T16:56:34.779+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.preprocess_train manual__2025-07-13T16:36:30+00:00 [queued]>
[2025-07-13T16:56:34.780+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-07-13T16:56:34.822+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): preprocess_train> on 2025-07-13 16:36:30+00:00
[2025-07-13T16:56:34.836+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=457) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T16:56:34.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'preprocess_train', 'manual__2025-07-13T16:36:30+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpmw585hzu']
[2025-07-13T16:56:34.855+0000] {standard_task_runner.py:72} INFO - Started process 463 to run task
[2025-07-13T16:56:34.862+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask preprocess_train
[2025-07-13T16:56:34.916+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T16:56:35.008+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.preprocess_train manual__2025-07-13T16:36:30+00:00 [running]> on host 6011aa489c7f
[2025-07-13T16:56:35.250+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_train' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:36:30+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:36:30+00:00'
[2025-07-13T16:56:35.253+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:56:35.280+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T16:56:35.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/preprocess.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --raw_table raw_turnstile_data                 --features_table turnstile_features                 --mode train\n        ']
[2025-07-13T16:56:35.303+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T16:56:37.837+0000] {subprocess.py:106} INFO - Loaded (2000, 10)
[2025-07-13T16:56:37.838+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T16:56:37.839+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/preprocess.py", line 103, in <module>
[2025-07-13T16:56:37.842+0000] {subprocess.py:106} INFO -     df_agg = preprocess(df_raw)
[2025-07-13T16:56:37.844+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^
[2025-07-13T16:56:37.846+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/preprocess.py", line 14, in preprocess
[2025-07-13T16:56:37.849+0000] {subprocess.py:106} INFO -     df_raw["entries"] = pd.to_numeric(df_raw["entries"], errors="coerce")
[2025-07-13T16:56:37.850+0000] {subprocess.py:106} INFO -                                       ~~~~~~^^^^^^^^^^^
[2025-07-13T16:56:37.851+0000] {subprocess.py:106} INFO - TypeError: 'NoneType' object is not subscriptable
[2025-07-13T16:56:38.072+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T16:56:38.092+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:56:38.101+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=preprocess_train, run_id=manual__2025-07-13T16:36:30+00:00, execution_date=20250713T163630, start_date=20250713T165634, end_date=20250713T165638
[2025-07-13T16:56:38.158+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:56:38.160+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task preprocess_train (Bash command failed. The command returned a non-zero exit code 1.; 463)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:56:38.218+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T16:56:38.273+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:56:38.285+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
