[2025-08-02T09:24:32.217+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-02T09:24:32.284+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T09:24:32.327+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T09:24:32.330+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-02T09:24:32.387+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-08-01 00:00:00+00:00
[2025-08-02T09:24:32.551+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6507) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-02T09:24:32.666+0000] {standard_task_runner.py:72} INFO - Started process 6516 to run task
[2025-08-02T09:24:32.771+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'scheduled__2025-08-01T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp_b3dkex2']
[2025-08-02T09:24:32.887+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask download_and_ingest
[2025-08-02T09:24:33.255+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-02T09:24:34.510+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [running]> on host c9afdf80b5d8
[2025-08-02T09:24:34.553+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-02T09:24:35.222+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='download_and_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-01T00:00:00+00:00'
[2025-08-02T09:24:35.230+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-02T09:24:35.356+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-02T09:24:35.375+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/download_ingest.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --table_name raw_turnstile_data\n        ']
[2025-08-02T09:24:35.427+0000] {subprocess.py:99} INFO - Output:
[2025-08-02T09:24:40.962+0000] {subprocess.py:106} INFO - 2025-08-02 09:24:40.961364+00:00
[2025-08-02T09:24:40.963+0000] {subprocess.py:106} INFO - [INFO] Fetching data for dates: []
[2025-08-02T09:24:40.964+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-08-02T09:24:40.966+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 70, in <module>
[2025-08-02T09:24:40.967+0000] {subprocess.py:106} INFO -     download_and_ingest(year=year,
[2025-08-02T09:24:40.968+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 28, in download_and_ingest
[2025-08-02T09:24:40.971+0000] {subprocess.py:106} INFO -     df_raw = pd.concat(dfs, ignore_index=True)
[2025-08-02T09:24:40.972+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T09:24:40.972+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
[2025-08-02T09:24:40.973+0000] {subprocess.py:106} INFO -     op = _Concatenator(
[2025-08-02T09:24:40.974+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^
[2025-08-02T09:24:40.974+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
[2025-08-02T09:24:40.974+0000] {subprocess.py:106} INFO -     objs, keys = self._clean_keys_and_objs(objs, keys)
[2025-08-02T09:24:40.975+0000] {subprocess.py:106} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T09:24:40.975+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
[2025-08-02T09:24:40.976+0000] {subprocess.py:106} INFO -     raise ValueError("No objects to concatenate")
[2025-08-02T09:24:40.977+0000] {subprocess.py:106} INFO - ValueError: No objects to concatenate
[2025-08-02T09:24:41.389+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-08-02T09:24:41.422+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T09:24:41.434+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, run_id=scheduled__2025-08-01T00:00:00+00:00, execution_date=20250801T000000, start_date=20250802T092432, end_date=20250802T092441
[2025-08-02T09:24:41.501+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-02T09:24:41.503+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 158 for task download_and_ingest (Bash command failed. The command returned a non-zero exit code 1.; 6516)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T09:24:41.567+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-02T09:24:41.620+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T09:24:41.632+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-08-02T16:13:09.841+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-02T16:13:09.866+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T16:13:09.878+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T16:13:09.879+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-02T16:13:09.897+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-08-01 00:00:00+00:00
[2025-08-02T16:13:09.931+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=34) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-02T16:13:09.930+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'scheduled__2025-08-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/turnstile_ml_pipeline.py', '--cfg-path', '/tmp/tmp13rienj_']
[2025-08-02T16:13:09.934+0000] {standard_task_runner.py:72} INFO - Started process 40 to run task
[2025-08-02T16:13:09.934+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask download_and_ingest
[2025-08-02T16:13:09.975+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-02T16:13:10.101+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-08-01T00:00:00+00:00 [running]> on host 947ed4ec172c
[2025-08-02T16:13:10.105+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-02T16:13:10.446+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='download_and_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-01T00:00:00+00:00'
[2025-08-02T16:13:10.452+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-02T16:13:10.718+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-02T16:13:10.724+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/download_ingest.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --table_name raw_turnstile_data\n        ']
[2025-08-02T16:13:10.787+0000] {subprocess.py:99} INFO - Output:
[2025-08-02T16:13:16.407+0000] {subprocess.py:106} INFO - 2025-08-02 16:13:16.405473+00:00
[2025-08-02T16:13:16.408+0000] {subprocess.py:106} INFO - [INFO] Fetching data for dates: []
[2025-08-02T16:13:16.409+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-08-02T16:13:16.411+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 70, in <module>
[2025-08-02T16:13:16.414+0000] {subprocess.py:106} INFO -     download_and_ingest(year=year,
[2025-08-02T16:13:16.416+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 28, in download_and_ingest
[2025-08-02T16:13:16.420+0000] {subprocess.py:106} INFO -     df_raw = pd.concat(dfs, ignore_index=True)
[2025-08-02T16:13:16.421+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T16:13:16.422+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
[2025-08-02T16:13:16.423+0000] {subprocess.py:106} INFO -     op = _Concatenator(
[2025-08-02T16:13:16.425+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^
[2025-08-02T16:13:16.426+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
[2025-08-02T16:13:16.428+0000] {subprocess.py:106} INFO -     objs, keys = self._clean_keys_and_objs(objs, keys)
[2025-08-02T16:13:16.430+0000] {subprocess.py:106} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-02T16:13:16.432+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
[2025-08-02T16:13:16.433+0000] {subprocess.py:106} INFO -     raise ValueError("No objects to concatenate")
[2025-08-02T16:13:16.435+0000] {subprocess.py:106} INFO - ValueError: No objects to concatenate
[2025-08-02T16:13:16.876+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-08-02T16:13:16.928+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T16:13:16.953+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, run_id=scheduled__2025-08-01T00:00:00+00:00, execution_date=20250801T000000, start_date=20250802T161309, end_date=20250802T161316
[2025-08-02T16:13:17.157+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-02T16:13:17.164+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task download_and_ingest (Bash command failed. The command returned a non-zero exit code 1.; 40)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-02T16:13:17.235+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-02T16:13:17.283+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T16:13:17.288+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
