[2025-07-13T10:51:04.529+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-13T10:51:04.530+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model'
[2025-07-13T10:51:04.583+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-13T10:51:04.584+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model'
[2025-07-13T10:51:04.649+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T10:51:04.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T10:51:04.668+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-13T10:51:04.704+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T10:51:04.713+0000] {standard_task_runner.py:57} INFO - Started process 1236 to run task
[2025-07-13T10:51:04.726+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp75nk4w43']
[2025-07-13T10:51:04.731+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask tune_model
[2025-07-13T10:51:04.776+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T10:51:04.914+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-13T10:51:04.916+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-12T00:00:00+00:00/task_id=tune_model'
[2025-07-13T10:51:04.919+0000] {task_command.py:416} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host 961842f4d5ed
[2025-07-13T10:51:05.067+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T10:51:05.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-13T10:51:05.071+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-13T10:51:05.086+0000] {subprocess.py:86} INFO - Output:
[2025-07-13T10:51:06.515+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-13T10:51:06.516+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/tune_model.py", line 4, in <module>
[2025-07-13T10:51:06.516+0000] {subprocess.py:93} INFO -     import mlflow
[2025-07-13T10:51:06.517+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'mlflow'
[2025-07-13T10:51:06.629+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-13T10:51:06.646+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T10:51:06.655+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, execution_date=20250712T000000, start_date=20250713T105104, end_date=20250713T105106
[2025-07-13T10:51:06.690+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 1236)
[2025-07-13T10:51:06.715+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-13T10:51:06.761+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T11:29:53.112+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T11:29:53.167+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T11:29:53.195+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T11:29:53.197+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T11:29:53.234+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T11:29:53.249+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T11:29:53.253+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-07-13T11:29:53.250+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp0o_4lnak']
[2025-07-13T11:29:53.260+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask tune_model
[2025-07-13T11:29:53.294+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T11:29:53.419+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host 4113a1335f50
[2025-07-13T11:29:53.423+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T11:29:53.591+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T11:29:53.593+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T11:29:53.630+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T11:29:53.632+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-13T11:29:53.649+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T11:30:05.367+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T11:30:05.370+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 11, in <module>
[2025-07-13T11:30:05.371+0000] {subprocess.py:106} INFO -     from xgboost import XGBRegressor
[2025-07-13T11:30:05.373+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'xgboost'
[2025-07-13T11:30:05.905+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T11:30:05.926+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T11:30:05.935+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=scheduled__2025-07-12T00:00:00+00:00, execution_date=20250712T000000, start_date=20250713T112953, end_date=20250713T113005
[2025-07-13T11:30:05.984+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T11:30:05.986+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 95)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T11:30:06.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T11:30:06.063+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T11:30:06.071+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-13T13:52:12.383+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T13:52:12.414+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T13:52:12.429+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T13:52:12.430+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T13:52:12.451+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T13:52:12.465+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T13:52:12.468+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2025-07-13T13:52:12.466+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpr5q_5bwi']
[2025-07-13T13:52:12.469+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask tune_model
[2025-07-13T13:52:12.492+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T13:52:12.552+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host 32b8035fd216
[2025-07-13T13:52:12.555+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T13:52:12.718+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T13:52:12.720+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T13:52:12.755+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T13:52:12.760+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-13T13:52:12.833+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T13:52:19.117+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T13:52:19.119+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 13, in <module>
[2025-07-13T13:52:19.120+0000] {subprocess.py:106} INFO -     from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
[2025-07-13T13:52:19.121+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'hyperopt'
[2025-07-13T13:52:19.653+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T13:52:19.701+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T13:52:19.717+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=scheduled__2025-07-12T00:00:00+00:00, execution_date=20250712T000000, start_date=20250713T135212, end_date=20250713T135219
[2025-07-13T13:52:19.782+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T13:52:19.783+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T13:52:19.846+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T13:52:19.902+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T13:52:19.914+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-13T14:13:22.559+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T14:13:22.593+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T14:13:22.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T14:13:22.612+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T14:13:22.632+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T14:13:22.645+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T14:13:22.647+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-07-13T14:13:22.646+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpeond4uvv']
[2025-07-13T14:13:22.649+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask tune_model
[2025-07-13T14:13:22.669+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T14:13:22.731+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host 7bf41c76e92f
[2025-07-13T14:13:22.734+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T14:13:22.850+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T14:13:22.851+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T14:13:22.871+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T14:13:22.873+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-13T14:13:22.889+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T14:13:30.473+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T14:13:30.474+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
[2025-07-13T14:13:30.475+0000] {subprocess.py:106} INFO -     return fn()
[2025-07-13T14:13:30.476+0000] {subprocess.py:106} INFO -            ^^^^
[2025-07-13T14:13:30.477+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
[2025-07-13T14:13:30.478+0000] {subprocess.py:106} INFO -     return _ConnectionFairy._checkout(self)
[2025-07-13T14:13:30.479+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.480+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
[2025-07-13T14:13:30.481+0000] {subprocess.py:106} INFO -     fairy = _ConnectionRecord.checkout(pool)
[2025-07-13T14:13:30.482+0000] {subprocess.py:106} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.483+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
[2025-07-13T14:13:30.484+0000] {subprocess.py:106} INFO -     rec = pool._do_get()
[2025-07-13T14:13:30.485+0000] {subprocess.py:106} INFO -           ^^^^^^^^^^^^^^
[2025-07-13T14:13:30.487+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
[2025-07-13T14:13:30.488+0000] {subprocess.py:106} INFO -     with util.safe_reraise():
[2025-07-13T14:13:30.489+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.490+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[2025-07-13T14:13:30.490+0000] {subprocess.py:106} INFO -     compat.raise_(
[2025-07-13T14:13:30.491+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-07-13T14:13:30.492+0000] {subprocess.py:106} INFO -     raise exception
[2025-07-13T14:13:30.493+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
[2025-07-13T14:13:30.494+0000] {subprocess.py:106} INFO -     return self._create_connection()
[2025-07-13T14:13:30.495+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.496+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
[2025-07-13T14:13:30.497+0000] {subprocess.py:106} INFO -     return _ConnectionRecord(self)
[2025-07-13T14:13:30.498+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.498+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
[2025-07-13T14:13:30.499+0000] {subprocess.py:106} INFO -     self.__connect()
[2025-07-13T14:13:30.500+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
[2025-07-13T14:13:30.501+0000] {subprocess.py:106} INFO -     with util.safe_reraise():
[2025-07-13T14:13:30.502+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.503+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[2025-07-13T14:13:30.504+0000] {subprocess.py:106} INFO -     compat.raise_(
[2025-07-13T14:13:30.506+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-07-13T14:13:30.507+0000] {subprocess.py:106} INFO -     raise exception
[2025-07-13T14:13:30.508+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
[2025-07-13T14:13:30.509+0000] {subprocess.py:106} INFO -     self.dbapi_connection = connection = pool._invoke_creator(self)
[2025-07-13T14:13:30.510+0000] {subprocess.py:106} INFO -                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.511+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
[2025-07-13T14:13:30.512+0000] {subprocess.py:106} INFO -     return dialect.connect(*cargs, **cparams)
[2025-07-13T14:13:30.513+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.514+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
[2025-07-13T14:13:30.515+0000] {subprocess.py:106} INFO -     return self.dbapi.connect(*cargs, **cparams)
[2025-07-13T14:13:30.516+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.517+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-07-13T14:13:30.518+0000] {subprocess.py:106} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-07-13T14:13:30.519+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.521+0000] {subprocess.py:106} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-07-13T14:13:30.522+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-13T14:13:30.523+0000] {subprocess.py:106} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-07-13T14:13:30.524+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-13T14:13:30.525+0000] {subprocess.py:106} INFO - 
[2025-07-13T14:13:30.526+0000] {subprocess.py:106} INFO - 
[2025-07-13T14:13:30.527+0000] {subprocess.py:106} INFO - The above exception was the direct cause of the following exception:
[2025-07-13T14:13:30.527+0000] {subprocess.py:106} INFO - 
[2025-07-13T14:13:30.528+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T14:13:30.529+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 28, in <module>
[2025-07-13T14:13:30.530+0000] {subprocess.py:106} INFO -     df = pd.read_sql(query, con=engine)
[2025-07-13T14:13:30.531+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.532+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 652, in read_sql
[2025-07-13T14:13:30.533+0000] {subprocess.py:106} INFO -     with pandasSQL_builder(con) as pandas_sql:
[2025-07-13T14:13:30.534+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.535+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 851, in pandasSQL_builder
[2025-07-13T14:13:30.536+0000] {subprocess.py:106} INFO -     return SQLDatabase(con, schema, need_transaction)
[2025-07-13T14:13:30.537+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.538+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1576, in __init__
[2025-07-13T14:13:30.539+0000] {subprocess.py:106} INFO -     con = self.exit_stack.enter_context(con.connect())
[2025-07-13T14:13:30.540+0000] {subprocess.py:106} INFO -                                         ^^^^^^^^^^^^^
[2025-07-13T14:13:30.540+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
[2025-07-13T14:13:30.541+0000] {subprocess.py:106} INFO -     return self._connection_cls(self, close_with_result=close_with_result)
[2025-07-13T14:13:30.542+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.543+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
[2025-07-13T14:13:30.543+0000] {subprocess.py:106} INFO -     else engine.raw_connection()
[2025-07-13T14:13:30.544+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.545+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
[2025-07-13T14:13:30.545+0000] {subprocess.py:106} INFO -     return self._wrap_pool_connect(self.pool.connect, _connection)
[2025-07-13T14:13:30.546+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.547+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
[2025-07-13T14:13:30.548+0000] {subprocess.py:106} INFO -     Connection._handle_dbapi_exception_noconnection(
[2025-07-13T14:13:30.548+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
[2025-07-13T14:13:30.549+0000] {subprocess.py:106} INFO -     util.raise_(
[2025-07-13T14:13:30.550+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-07-13T14:13:30.550+0000] {subprocess.py:106} INFO -     raise exception
[2025-07-13T14:13:30.551+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
[2025-07-13T14:13:30.552+0000] {subprocess.py:106} INFO -     return fn()
[2025-07-13T14:13:30.557+0000] {subprocess.py:106} INFO -            ^^^^
[2025-07-13T14:13:30.558+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
[2025-07-13T14:13:30.559+0000] {subprocess.py:106} INFO -     return _ConnectionFairy._checkout(self)
[2025-07-13T14:13:30.559+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.560+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
[2025-07-13T14:13:30.561+0000] {subprocess.py:106} INFO -     fairy = _ConnectionRecord.checkout(pool)
[2025-07-13T14:13:30.561+0000] {subprocess.py:106} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.562+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
[2025-07-13T14:13:30.562+0000] {subprocess.py:106} INFO -     rec = pool._do_get()
[2025-07-13T14:13:30.563+0000] {subprocess.py:106} INFO -           ^^^^^^^^^^^^^^
[2025-07-13T14:13:30.564+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
[2025-07-13T14:13:30.564+0000] {subprocess.py:106} INFO -     with util.safe_reraise():
[2025-07-13T14:13:30.565+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.565+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[2025-07-13T14:13:30.566+0000] {subprocess.py:106} INFO -     compat.raise_(
[2025-07-13T14:13:30.567+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-07-13T14:13:30.567+0000] {subprocess.py:106} INFO -     raise exception
[2025-07-13T14:13:30.568+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
[2025-07-13T14:13:30.569+0000] {subprocess.py:106} INFO -     return self._create_connection()
[2025-07-13T14:13:30.569+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.570+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
[2025-07-13T14:13:30.571+0000] {subprocess.py:106} INFO -     return _ConnectionRecord(self)
[2025-07-13T14:13:30.572+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.572+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
[2025-07-13T14:13:30.573+0000] {subprocess.py:106} INFO -     self.__connect()
[2025-07-13T14:13:30.574+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
[2025-07-13T14:13:30.574+0000] {subprocess.py:106} INFO -     with util.safe_reraise():
[2025-07-13T14:13:30.575+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.575+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[2025-07-13T14:13:30.576+0000] {subprocess.py:106} INFO -     compat.raise_(
[2025-07-13T14:13:30.577+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[2025-07-13T14:13:30.577+0000] {subprocess.py:106} INFO -     raise exception
[2025-07-13T14:13:30.578+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
[2025-07-13T14:13:30.578+0000] {subprocess.py:106} INFO -     self.dbapi_connection = connection = pool._invoke_creator(self)
[2025-07-13T14:13:30.579+0000] {subprocess.py:106} INFO -                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.580+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
[2025-07-13T14:13:30.580+0000] {subprocess.py:106} INFO -     return dialect.connect(*cargs, **cparams)
[2025-07-13T14:13:30.581+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.581+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
[2025-07-13T14:13:30.582+0000] {subprocess.py:106} INFO -     return self.dbapi.connect(*cargs, **cparams)
[2025-07-13T14:13:30.583+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.583+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-07-13T14:13:30.584+0000] {subprocess.py:106} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-07-13T14:13:30.585+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T14:13:30.585+0000] {subprocess.py:106} INFO - sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-07-13T14:13:30.586+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-13T14:13:30.586+0000] {subprocess.py:106} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-07-13T14:13:30.587+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-13T14:13:30.588+0000] {subprocess.py:106} INFO - 
[2025-07-13T14:13:30.588+0000] {subprocess.py:106} INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-13T14:13:30.956+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T14:13:30.971+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T14:13:30.978+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=scheduled__2025-07-12T00:00:00+00:00, execution_date=20250712T000000, start_date=20250713T141322, end_date=20250713T141330
[2025-07-13T14:13:31.017+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T14:13:31.019+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 112)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T14:13:31.069+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T14:13:31.104+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T14:13:31.110+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-13T16:18:16.815+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:18:16.856+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T16:18:16.875+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T16:18:16.876+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T16:18:16.898+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T16:18:16.912+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T16:18:16.912+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp3xjtfkek']
[2025-07-13T16:18:16.914+0000] {standard_task_runner.py:72} INFO - Started process 168 to run task
[2025-07-13T16:18:16.915+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask tune_model
[2025-07-13T16:18:16.938+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T16:18:17.010+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host 6011aa489c7f
[2025-07-13T16:18:17.013+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T16:18:17.142+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T16:18:17.144+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:18:17.171+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T16:18:17.173+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --features_table turnstile_features         ']
[2025-07-13T16:18:17.192+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T16:18:24.124+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]2025/07/13 16:18:24 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-07-13T16:18:24.125+0000] {subprocess.py:106} INFO - The git executable must be specified in one of the following ways:
[2025-07-13T16:18:24.126+0000] {subprocess.py:106} INFO -     - be included in your $PATH
[2025-07-13T16:18:24.127+0000] {subprocess.py:106} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-07-13T16:18:24.128+0000] {subprocess.py:106} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-07-13T16:18:24.129+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:24.129+0000] {subprocess.py:106} INFO - All git commands will error until this is rectified.
[2025-07-13T16:18:24.130+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:24.131+0000] {subprocess.py:106} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-07-13T16:18:24.132+0000] {subprocess.py:106} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-07-13T16:18:24.132+0000] {subprocess.py:106} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-07-13T16:18:24.133+0000] {subprocess.py:106} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-07-13T16:18:24.134+0000] {subprocess.py:106} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-07-13T16:18:24.135+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:24.136+0000] {subprocess.py:106} INFO - Example:
[2025-07-13T16:18:24.137+0000] {subprocess.py:106} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-07-13T16:18:24.138+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:24.138+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:25.378+0000] {subprocess.py:106} INFO -                                                       🏃 View run tune-20250713-161824 at: http://mlflow:5000/#/experiments/1/runs/1ae6a3a3d4aa4349b05d9d27ed758e87
[2025-07-13T16:18:25.379+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:25.380+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T16:18:25.381+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:25.434+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]job exception: Experimental support for categorical data is not implemented for current tree method yet.
[2025-07-13T16:18:25.436+0000] {subprocess.py:106} INFO - 
[2025-07-13T16:18:25.437+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]
[2025-07-13T16:18:25.438+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T16:18:25.438+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 117, in <module>
[2025-07-13T16:18:25.439+0000] {subprocess.py:106} INFO -     tune(df, args.experiment_name, args.run_prefix, args.n_trials)
[2025-07-13T16:18:25.442+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 76, in tune
[2025-07-13T16:18:25.445+0000] {subprocess.py:106} INFO -     best_result = fmin(
[2025-07-13T16:18:25.446+0000] {subprocess.py:106} INFO -                   ^^^^^
[2025-07-13T16:18:25.447+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 540, in fmin
[2025-07-13T16:18:25.448+0000] {subprocess.py:106} INFO -     return trials.fmin(
[2025-07-13T16:18:25.449+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-07-13T16:18:25.450+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/base.py", line 671, in fmin
[2025-07-13T16:18:25.450+0000] {subprocess.py:106} INFO -     return fmin(
[2025-07-13T16:18:25.451+0000] {subprocess.py:106} INFO -            ^^^^^
[2025-07-13T16:18:25.452+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 586, in fmin
[2025-07-13T16:18:25.452+0000] {subprocess.py:106} INFO -     rval.exhaust()
[2025-07-13T16:18:25.453+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 364, in exhaust
[2025-07-13T16:18:25.454+0000] {subprocess.py:106} INFO -     self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
[2025-07-13T16:18:25.455+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 300, in run
[2025-07-13T16:18:25.455+0000] {subprocess.py:106} INFO -     self.serial_evaluate()
[2025-07-13T16:18:25.456+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
[2025-07-13T16:18:25.458+0000] {subprocess.py:106} INFO -     result = self.domain.evaluate(spec, ctrl)
[2025-07-13T16:18:25.459+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:18:25.460+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/hyperopt/base.py", line 892, in evaluate
[2025-07-13T16:18:25.461+0000] {subprocess.py:106} INFO -     rval = self.fn(pyll_rval)
[2025-07-13T16:18:25.462+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^
[2025-07-13T16:18:25.463+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 65, in objective
[2025-07-13T16:18:25.464+0000] {subprocess.py:106} INFO -     model.fit(X_train, y_train)
[2025-07-13T16:18:25.465+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/xgboost/core.py", line 620, in inner_f
[2025-07-13T16:18:25.466+0000] {subprocess.py:106} INFO -     return func(**kwargs)
[2025-07-13T16:18:25.467+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^
[2025-07-13T16:18:25.467+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/xgboost/sklearn.py", line 1022, in fit
[2025-07-13T16:18:25.468+0000] {subprocess.py:106} INFO -     ) = self._configure_fit(
[2025-07-13T16:18:25.469+0000] {subprocess.py:106} INFO -         ^^^^^^^^^^^^^^^^^^^^
[2025-07-13T16:18:25.470+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/xgboost/sklearn.py", line 892, in _configure_fit
[2025-07-13T16:18:25.471+0000] {subprocess.py:106} INFO -     raise ValueError(
[2025-07-13T16:18:25.471+0000] {subprocess.py:106} INFO - ValueError: Experimental support for categorical data is not implemented for current tree method yet.
[2025-07-13T16:18:26.121+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T16:18:26.139+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:18:26.147+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=scheduled__2025-07-12T00:00:00+00:00, execution_date=20250712T000000, start_date=20250713T161816, end_date=20250713T161826
[2025-07-13T16:18:26.188+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:18:26.190+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 168)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T16:18:26.238+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T16:18:26.275+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:18:26.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-13T17:17:34.739+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T17:17:34.777+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T17:17:34.809+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-13T17:17:34.810+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T17:17:34.844+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-12 00:00:00+00:00
[2025-07-13T17:17:34.860+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T17:17:34.865+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-07-13T17:17:34.872+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpaftfduq5']
[2025-07-13T17:17:34.877+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask tune_model
[2025-07-13T17:17:34.903+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T17:17:34.980+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-12T00:00:00+00:00 [running]> on host d84888688479
[2025-07-13T17:17:34.983+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T17:17:35.113+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-13T17:17:35.115+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T17:17:35.143+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T17:17:35.146+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --features_table turnstile_features         ']
[2025-07-13T17:17:35.163+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T17:17:41.585+0000] {subprocess.py:106} INFO - /opt/***/pipeline/tune_model.py:44: SettingWithCopyWarning:
[2025-07-13T17:17:41.586+0000] {subprocess.py:106} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-07-13T17:17:41.587+0000] {subprocess.py:106} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-07-13T17:17:41.588+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:41.588+0000] {subprocess.py:106} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-07-13T17:17:41.589+0000] {subprocess.py:106} INFO -   X_train[col] = pd.to_numeric(X_train[col], errors="coerce")
[2025-07-13T17:17:41.590+0000] {subprocess.py:106} INFO - /opt/***/pipeline/tune_model.py:45: SettingWithCopyWarning:
[2025-07-13T17:17:41.590+0000] {subprocess.py:106} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-07-13T17:17:41.591+0000] {subprocess.py:106} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-07-13T17:17:41.591+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:41.592+0000] {subprocess.py:106} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-07-13T17:17:41.592+0000] {subprocess.py:106} INFO -   X_val[col] = pd.to_numeric(X_val[col], errors="coerce")
[2025-07-13T17:17:41.593+0000] {subprocess.py:106} INFO - /opt/***/pipeline/tune_model.py:46: SettingWithCopyWarning:
[2025-07-13T17:17:41.594+0000] {subprocess.py:106} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-07-13T17:17:41.595+0000] {subprocess.py:106} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-07-13T17:17:41.596+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:41.597+0000] {subprocess.py:106} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-07-13T17:17:41.598+0000] {subprocess.py:106} INFO -   X_train["group_key"] = X_train["group_key"].astype("category")
[2025-07-13T17:17:41.599+0000] {subprocess.py:106} INFO - /opt/***/pipeline/tune_model.py:47: SettingWithCopyWarning:
[2025-07-13T17:17:41.600+0000] {subprocess.py:106} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-07-13T17:17:41.601+0000] {subprocess.py:106} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-07-13T17:17:41.602+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:41.603+0000] {subprocess.py:106} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-07-13T17:17:41.603+0000] {subprocess.py:106} INFO -   X_val["group_key"] = X_val["group_key"].astype("category")
[2025-07-13T17:17:42.820+0000] {subprocess.py:106} INFO - Train shape: (118, 8)
[2025-07-13T17:17:42.821+0000] {subprocess.py:106} INFO - Validation shape: (142, 8)
[2025-07-13T17:17:42.822+0000] {subprocess.py:106} INFO - Max datetime in dataset: 2022-06-29 22:00:00
[2025-07-13T17:17:42.894+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:00<?, ?trial/s, best loss=?]2025/07/13 17:17:42 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-07-13T17:17:42.895+0000] {subprocess.py:106} INFO - The git executable must be specified in one of the following ways:
[2025-07-13T17:17:42.897+0000] {subprocess.py:106} INFO -     - be included in your $PATH
[2025-07-13T17:17:42.898+0000] {subprocess.py:106} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-07-13T17:17:42.899+0000] {subprocess.py:106} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-07-13T17:17:42.900+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:42.901+0000] {subprocess.py:106} INFO - All git commands will error until this is rectified.
[2025-07-13T17:17:42.901+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:42.902+0000] {subprocess.py:106} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-07-13T17:17:42.903+0000] {subprocess.py:106} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-07-13T17:17:42.904+0000] {subprocess.py:106} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-07-13T17:17:42.905+0000] {subprocess.py:106} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-07-13T17:17:42.906+0000] {subprocess.py:106} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-07-13T17:17:42.906+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:42.907+0000] {subprocess.py:106} INFO - Example:
[2025-07-13T17:17:42.908+0000] {subprocess.py:106} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-07-13T17:17:42.909+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:42.910+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:44.179+0000] {subprocess.py:106} INFO -                                                       [17:17:44] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:44.183+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:44.188+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:46.045+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:01<?, ?trial/s, best loss=?]                                                      🏃 View run tune-20250713-171742 at: http://mlflow:5000/#/experiments/1/runs/d4c4f59ea4b44759b5991f71eddbd672
[2025-07-13T17:17:46.053+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:46.060+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:03<?, ?trial/s, best loss=?]                                                      🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:17:46.061+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:46.394+0000] {subprocess.py:106} INFO -   0%|          | 0/30 [00:03<?, ?trial/s, best loss=?]  3%|▎         | 1/30 [00:03<01:36,  3.33s/trial, best loss: 1531.6367819346433]                                                                                [17:17:46] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:46.403+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:46.406+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:51.019+0000] {subprocess.py:106} INFO -   3%|▎         | 1/30 [00:03<01:36,  3.33s/trial, best loss: 1531.6367819346433]                                                                                🏃 View run tune-20250713-171746 at: http://mlflow:5000/#/experiments/1/runs/6467b35499924f7cb224c98b43513f34
[2025-07-13T17:17:51.020+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:51.022+0000] {subprocess.py:106} INFO -   3%|▎         | 1/30 [00:08<01:36,  3.33s/trial, best loss: 1531.6367819346433]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:17:51.023+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:51.420+0000] {subprocess.py:106} INFO -   3%|▎         | 1/30 [00:08<01:36,  3.33s/trial, best loss: 1531.6367819346433]  7%|▋         | 2/30 [00:08<01:59,  4.28s/trial, best loss: 1414.4273106324608]                                                                                [17:17:51] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:51.422+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:51.427+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:51.887+0000] {subprocess.py:106} INFO -   7%|▋         | 2/30 [00:08<01:59,  4.28s/trial, best loss: 1414.4273106324608]                                                                                🏃 View run tune-20250713-171751 at: http://mlflow:5000/#/experiments/1/runs/cd615b57ab154c508cebbff58ce2f255
[2025-07-13T17:17:51.888+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:51.890+0000] {subprocess.py:106} INFO -   7%|▋         | 2/30 [00:09<01:59,  4.28s/trial, best loss: 1414.4273106324608]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:17:51.891+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:52.234+0000] {subprocess.py:106} INFO -   7%|▋         | 2/30 [00:09<01:59,  4.28s/trial, best loss: 1414.4273106324608] 10%|█         | 3/30 [00:09<01:13,  2.72s/trial, best loss: 568.5299046574163]                                                                                [17:17:52] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:52.243+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:52.244+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:54.320+0000] {subprocess.py:106} INFO -  10%|█         | 3/30 [00:09<01:13,  2.72s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171751 at: http://mlflow:5000/#/experiments/1/runs/7bce3be9d40c44c9aa15a6515ae75d6b
[2025-07-13T17:17:54.322+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:54.323+0000] {subprocess.py:106} INFO -  10%|█         | 3/30 [00:11<01:13,  2.72s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:17:54.324+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:54.611+0000] {subprocess.py:106} INFO -  10%|█         | 3/30 [00:11<01:13,  2.72s/trial, best loss: 568.5299046574163] 13%|█▎        | 4/30 [00:11<01:07,  2.60s/trial, best loss: 568.5299046574163]                                                                               [17:17:54] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:54.613+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:54.614+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:57.535+0000] {subprocess.py:106} INFO -  13%|█▎        | 4/30 [00:11<01:07,  2.60s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171754 at: http://mlflow:5000/#/experiments/1/runs/c8fe7d27950342009107cf0dcd6199a5
[2025-07-13T17:17:57.537+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:57.537+0000] {subprocess.py:106} INFO -  13%|█▎        | 4/30 [00:14<01:07,  2.60s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:17:57.538+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:17:57.854+0000] {subprocess.py:106} INFO -  13%|█▎        | 4/30 [00:14<01:07,  2.60s/trial, best loss: 568.5299046574163] 17%|█▋        | 5/30 [00:14<01:10,  2.82s/trial, best loss: 568.5299046574163]                                                                               [17:17:57] WARNING: ../src/learner.cc:767:
[2025-07-13T17:17:57.859+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:17:57.863+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:00.330+0000] {subprocess.py:106} INFO -  17%|█▋        | 5/30 [00:15<01:10,  2.82s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171757 at: http://mlflow:5000/#/experiments/1/runs/60be7da8e77b4293a30197d246848f58
[2025-07-13T17:18:00.331+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:00.331+0000] {subprocess.py:106} INFO -  17%|█▋        | 5/30 [00:17<01:10,  2.82s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:00.333+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:00.786+0000] {subprocess.py:106} INFO -  17%|█▋        | 5/30 [00:17<01:10,  2.82s/trial, best loss: 568.5299046574163] 20%|██        | 6/30 [00:17<01:07,  2.82s/trial, best loss: 568.5299046574163]                                                                               [17:18:00] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:00.791+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:00.793+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:03.698+0000] {subprocess.py:106} INFO -  20%|██        | 6/30 [00:17<01:07,  2.82s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171800 at: http://mlflow:5000/#/experiments/1/runs/8c1840866ad04453b5c3558dc9b3ae2d
[2025-07-13T17:18:03.700+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:03.701+0000] {subprocess.py:106} INFO -  20%|██        | 6/30 [00:20<01:07,  2.82s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:03.702+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:04.108+0000] {subprocess.py:106} INFO -  20%|██        | 6/30 [00:20<01:07,  2.82s/trial, best loss: 568.5299046574163] 23%|██▎       | 7/30 [00:20<01:08,  3.00s/trial, best loss: 568.5299046574163]                                                                               [17:18:04] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:04.123+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:04.128+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:04.761+0000] {subprocess.py:106} INFO -  23%|██▎       | 7/30 [00:21<01:08,  3.00s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171803 at: http://mlflow:5000/#/experiments/1/runs/07c1e9b5d5d34e2190a9f970b97a8b32
[2025-07-13T17:18:04.763+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:04.764+0000] {subprocess.py:106} INFO -  23%|██▎       | 7/30 [00:21<01:08,  3.00s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:04.765+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:05.178+0000] {subprocess.py:106} INFO -  23%|██▎       | 7/30 [00:21<01:08,  3.00s/trial, best loss: 568.5299046574163] 27%|██▋       | 8/30 [00:22<00:52,  2.38s/trial, best loss: 568.5299046574163]                                                                               [17:18:05] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:05.185+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:05.186+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:06.835+0000] {subprocess.py:106} INFO -  27%|██▋       | 8/30 [00:22<00:52,  2.38s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171804 at: http://mlflow:5000/#/experiments/1/runs/8ea214cae74b446c857fd3384edb90e4
[2025-07-13T17:18:06.836+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:06.837+0000] {subprocess.py:106} INFO -  27%|██▋       | 8/30 [00:24<00:52,  2.38s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:06.837+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:07.149+0000] {subprocess.py:106} INFO -  27%|██▋       | 8/30 [00:24<00:52,  2.38s/trial, best loss: 568.5299046574163] 30%|███       | 9/30 [00:24<00:47,  2.28s/trial, best loss: 568.5299046574163]                                                                               [17:18:07] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:07.160+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:07.175+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:07.559+0000] {subprocess.py:106} INFO -  30%|███       | 9/30 [00:24<00:47,  2.28s/trial, best loss: 568.5299046574163]                                                                               🏃 View run tune-20250713-171806 at: http://mlflow:5000/#/experiments/1/runs/2c8ae3fced67403e81b7459f6d008c71
[2025-07-13T17:18:07.562+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:07.563+0000] {subprocess.py:106} INFO -  30%|███       | 9/30 [00:24<00:47,  2.28s/trial, best loss: 568.5299046574163]                                                                               🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:07.564+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:07.877+0000] {subprocess.py:106} INFO -  30%|███       | 9/30 [00:24<00:47,  2.28s/trial, best loss: 568.5299046574163] 33%|███▎      | 10/30 [00:24<00:35,  1.80s/trial, best loss: 568.5299046574163]                                                                                [17:18:07] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:07.884+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:07.885+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:10.696+0000] {subprocess.py:106} INFO -  33%|███▎      | 10/30 [00:25<00:35,  1.80s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171807 at: http://mlflow:5000/#/experiments/1/runs/27883791d8844b50ae4495cb03c38a0b
[2025-07-13T17:18:10.697+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:10.698+0000] {subprocess.py:106} INFO -  33%|███▎      | 10/30 [00:27<00:35,  1.80s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:10.699+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:11.009+0000] {subprocess.py:106} INFO -  33%|███▎      | 10/30 [00:27<00:35,  1.80s/trial, best loss: 568.5299046574163] 37%|███▋      | 11/30 [00:27<00:42,  2.21s/trial, best loss: 568.5299046574163]                                                                                [17:18:11] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:11.010+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:11.011+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:14.850+0000] {subprocess.py:106} INFO -  37%|███▋      | 11/30 [00:28<00:42,  2.21s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171810 at: http://mlflow:5000/#/experiments/1/runs/3e1fecde1c974540b13428e1f6e14fa9
[2025-07-13T17:18:14.852+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:14.853+0000] {subprocess.py:106} INFO -  37%|███▋      | 11/30 [00:32<00:42,  2.21s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:14.854+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:15.178+0000] {subprocess.py:106} INFO -  37%|███▋      | 11/30 [00:32<00:42,  2.21s/trial, best loss: 568.5299046574163] 40%|████      | 12/30 [00:32<00:50,  2.80s/trial, best loss: 568.5299046574163]                                                                                [17:18:15] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:15.187+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:15.189+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:19.383+0000] {subprocess.py:106} INFO -  40%|████      | 12/30 [00:32<00:50,  2.80s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171814 at: http://mlflow:5000/#/experiments/1/runs/89bd2682e57e4353aa6461a00e2e2ce8
[2025-07-13T17:18:19.385+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:19.386+0000] {subprocess.py:106} INFO -  40%|████      | 12/30 [00:36<00:50,  2.80s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:19.398+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:19.782+0000] {subprocess.py:106} INFO -  40%|████      | 12/30 [00:36<00:50,  2.80s/trial, best loss: 568.5299046574163] 43%|████▎     | 13/30 [00:36<00:56,  3.33s/trial, best loss: 568.5299046574163]                                                                                [17:18:19] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:19.787+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:19.796+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:22.690+0000] {subprocess.py:106} INFO -  43%|████▎     | 13/30 [00:36<00:56,  3.33s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171819 at: http://mlflow:5000/#/experiments/1/runs/b59ee262954040d7bb5afba357654527
[2025-07-13T17:18:22.692+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:22.693+0000] {subprocess.py:106} INFO -  43%|████▎     | 13/30 [00:39<00:56,  3.33s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:22.694+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:23.009+0000] {subprocess.py:106} INFO -  43%|████▎     | 13/30 [00:39<00:56,  3.33s/trial, best loss: 568.5299046574163] 47%|████▋     | 14/30 [00:39<00:53,  3.32s/trial, best loss: 568.5299046574163]                                                                                [17:18:23] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:23.024+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:23.029+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:25.947+0000] {subprocess.py:106} INFO -  47%|████▋     | 14/30 [00:40<00:53,  3.32s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171822 at: http://mlflow:5000/#/experiments/1/runs/b92f8268db3348f0b1433bf8316f382f
[2025-07-13T17:18:25.948+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:25.949+0000] {subprocess.py:106} INFO -  47%|████▋     | 14/30 [00:43<00:53,  3.32s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:25.951+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:26.339+0000] {subprocess.py:106} INFO -  47%|████▋     | 14/30 [00:43<00:53,  3.32s/trial, best loss: 568.5299046574163] 50%|█████     | 15/30 [00:43<00:49,  3.30s/trial, best loss: 568.5299046574163]                                                                                [17:18:26] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:26.340+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:26.341+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:26.875+0000] {subprocess.py:106} INFO -  50%|█████     | 15/30 [00:43<00:49,  3.30s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171826 at: http://mlflow:5000/#/experiments/1/runs/8d52cef47c6647c68d74e18a748db439
[2025-07-13T17:18:26.876+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:26.878+0000] {subprocess.py:106} INFO -  50%|█████     | 15/30 [00:44<00:49,  3.30s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:26.880+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:27.174+0000] {subprocess.py:106} INFO -  50%|█████     | 15/30 [00:44<00:49,  3.30s/trial, best loss: 568.5299046574163] 53%|█████▎    | 16/30 [00:44<00:36,  2.59s/trial, best loss: 568.5299046574163]                                                                                [17:18:27] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:27.176+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:27.177+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:27.905+0000] {subprocess.py:106} INFO -  53%|█████▎    | 16/30 [00:44<00:36,  2.59s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171826 at: http://mlflow:5000/#/experiments/1/runs/923635b63bbd439683327761e99d719f
[2025-07-13T17:18:27.907+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:27.908+0000] {subprocess.py:106} INFO -  53%|█████▎    | 16/30 [00:45<00:36,  2.59s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:27.909+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:28.357+0000] {subprocess.py:106} INFO -  53%|█████▎    | 16/30 [00:45<00:36,  2.59s/trial, best loss: 568.5299046574163] 57%|█████▋    | 17/30 [00:45<00:27,  2.12s/trial, best loss: 568.5299046574163]                                                                                [17:18:28] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:28.359+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:28.360+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:30.298+0000] {subprocess.py:106} INFO -  57%|█████▋    | 17/30 [00:45<00:27,  2.12s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171827 at: http://mlflow:5000/#/experiments/1/runs/a7a0bee765244ee09a333c3db1fce9da
[2025-07-13T17:18:30.300+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:30.301+0000] {subprocess.py:106} INFO -  57%|█████▋    | 17/30 [00:47<00:27,  2.12s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:30.302+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:30.721+0000] {subprocess.py:106} INFO -  57%|█████▋    | 17/30 [00:47<00:27,  2.12s/trial, best loss: 568.5299046574163] 60%|██████    | 18/30 [00:47<00:26,  2.21s/trial, best loss: 568.5299046574163]                                                                                [17:18:30] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:30.723+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:30.727+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:31.245+0000] {subprocess.py:106} INFO -  60%|██████    | 18/30 [00:47<00:26,  2.21s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171830 at: http://mlflow:5000/#/experiments/1/runs/86527a4b9a5e413b95fb7bb3edd8bf77
[2025-07-13T17:18:31.245+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:31.246+0000] {subprocess.py:106} INFO -  60%|██████    | 18/30 [00:48<00:26,  2.21s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:31.247+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:31.628+0000] {subprocess.py:106} INFO -  60%|██████    | 18/30 [00:48<00:26,  2.21s/trial, best loss: 568.5299046574163] 63%|██████▎   | 19/30 [00:48<00:20,  1.82s/trial, best loss: 568.5299046574163]                                                                                [17:18:31] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:31.632+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:31.633+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:34.718+0000] {subprocess.py:106} INFO -  63%|██████▎   | 19/30 [00:48<00:20,  1.82s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171831 at: http://mlflow:5000/#/experiments/1/runs/3ee0e7a6f35840a98073b2e52e11d805
[2025-07-13T17:18:34.719+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:34.720+0000] {subprocess.py:106} INFO -  63%|██████▎   | 19/30 [00:51<00:20,  1.82s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:34.720+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:35.108+0000] {subprocess.py:106} INFO -  63%|██████▎   | 19/30 [00:51<00:20,  1.82s/trial, best loss: 568.5299046574163] 67%|██████▋   | 20/30 [00:51<00:23,  2.32s/trial, best loss: 568.5299046574163]                                                                                [17:18:35] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:35.109+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:35.110+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:37.835+0000] {subprocess.py:106} INFO -  67%|██████▋   | 20/30 [00:52<00:23,  2.32s/trial, best loss: 568.5299046574163]                                                                                🏃 View run tune-20250713-171834 at: http://mlflow:5000/#/experiments/1/runs/e54f6e6a36e44f7091444cebe82ac27c
[2025-07-13T17:18:37.836+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:37.837+0000] {subprocess.py:106} INFO -  67%|██████▋   | 20/30 [00:55<00:23,  2.32s/trial, best loss: 568.5299046574163]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:37.838+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:38.225+0000] {subprocess.py:106} INFO -  67%|██████▋   | 20/30 [00:55<00:23,  2.32s/trial, best loss: 568.5299046574163] 70%|███████   | 21/30 [00:55<00:23,  2.56s/trial, best loss: 555.6339008331669]                                                                                [17:18:38] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:38.234+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:38.238+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:40.790+0000] {subprocess.py:106} INFO -  70%|███████   | 21/30 [00:55<00:23,  2.56s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171837 at: http://mlflow:5000/#/experiments/1/runs/a1b864a3115f461c88e8b666acef075c
[2025-07-13T17:18:40.792+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:40.792+0000] {subprocess.py:106} INFO -  70%|███████   | 21/30 [00:57<00:23,  2.56s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:40.793+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:41.264+0000] {subprocess.py:106} INFO -  70%|███████   | 21/30 [00:57<00:23,  2.56s/trial, best loss: 555.6339008331669] 73%|███████▎  | 22/30 [00:58<00:21,  2.68s/trial, best loss: 555.6339008331669]                                                                                [17:18:41] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:41.265+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:41.265+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:41.925+0000] {subprocess.py:106} INFO -  73%|███████▎  | 22/30 [00:58<00:21,  2.68s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171840 at: http://mlflow:5000/#/experiments/1/runs/a4e5552321604df69446c96383e766f5
[2025-07-13T17:18:41.926+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:41.927+0000] {subprocess.py:106} INFO -  73%|███████▎  | 22/30 [00:59<00:21,  2.68s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:41.928+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:42.322+0000] {subprocess.py:106} INFO -  73%|███████▎  | 22/30 [00:59<00:21,  2.68s/trial, best loss: 555.6339008331669] 77%|███████▋  | 23/30 [00:59<00:15,  2.22s/trial, best loss: 555.6339008331669]                                                                                [17:18:42] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:42.323+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:42.324+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:45.576+0000] {subprocess.py:106} INFO -  77%|███████▋  | 23/30 [00:59<00:15,  2.22s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171842 at: http://mlflow:5000/#/experiments/1/runs/e9b1123cf22b4b3bb88b88eaf904e85d
[2025-07-13T17:18:45.577+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:45.578+0000] {subprocess.py:106} INFO -  77%|███████▋  | 23/30 [01:02<00:15,  2.22s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:45.578+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:45.975+0000] {subprocess.py:106} INFO -  77%|███████▋  | 23/30 [01:02<00:15,  2.22s/trial, best loss: 555.6339008331669] 80%|████████  | 24/30 [01:02<00:15,  2.64s/trial, best loss: 555.6339008331669]                                                                                [17:18:45] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:45.977+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:45.979+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:49.682+0000] {subprocess.py:106} INFO -  80%|████████  | 24/30 [01:03<00:15,  2.64s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171845 at: http://mlflow:5000/#/experiments/1/runs/8f3d6341ff9143c1b60837d21a16245a
[2025-07-13T17:18:49.683+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:49.684+0000] {subprocess.py:106} INFO -  80%|████████  | 24/30 [01:06<00:15,  2.64s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:49.684+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:50.037+0000] {subprocess.py:106} INFO -  80%|████████  | 24/30 [01:06<00:15,  2.64s/trial, best loss: 555.6339008331669] 83%|████████▎ | 25/30 [01:06<00:15,  3.08s/trial, best loss: 555.6339008331669]                                                                                [17:18:50] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:50.041+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:50.045+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:53.499+0000] {subprocess.py:106} INFO -  83%|████████▎ | 25/30 [01:07<00:15,  3.08s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171849 at: http://mlflow:5000/#/experiments/1/runs/1455901464b64e3e9c4ef5f825ccc572
[2025-07-13T17:18:53.500+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:53.501+0000] {subprocess.py:106} INFO -  83%|████████▎ | 25/30 [01:10<00:15,  3.08s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:53.502+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:53.872+0000] {subprocess.py:106} INFO -  83%|████████▎ | 25/30 [01:10<00:15,  3.08s/trial, best loss: 555.6339008331669] 87%|████████▋ | 26/30 [01:10<00:13,  3.30s/trial, best loss: 555.6339008331669]                                                                                [17:18:53] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:53.879+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:53.884+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:55.122+0000] {subprocess.py:106} INFO -  87%|████████▋ | 26/30 [01:11<00:13,  3.30s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171853 at: http://mlflow:5000/#/experiments/1/runs/d2f9e75a73044f74b12698b4fa2a662a
[2025-07-13T17:18:55.124+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:55.125+0000] {subprocess.py:106} INFO -  87%|████████▋ | 26/30 [01:12<00:13,  3.30s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:55.127+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:55.616+0000] {subprocess.py:106} INFO -  87%|████████▋ | 26/30 [01:12<00:13,  3.30s/trial, best loss: 555.6339008331669] 90%|█████████ | 27/30 [01:12<00:08,  2.80s/trial, best loss: 555.6339008331669]                                                                                [17:18:55] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:55.624+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:55.631+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:58.353+0000] {subprocess.py:106} INFO -  90%|█████████ | 27/30 [01:12<00:08,  2.80s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171855 at: http://mlflow:5000/#/experiments/1/runs/f941b382bec847e5b63f1b476de38b89
[2025-07-13T17:18:58.355+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:58.356+0000] {subprocess.py:106} INFO -  90%|█████████ | 27/30 [01:15<00:08,  2.80s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:18:58.356+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:18:58.773+0000] {subprocess.py:106} INFO -  90%|█████████ | 27/30 [01:15<00:08,  2.80s/trial, best loss: 555.6339008331669] 93%|█████████▎| 28/30 [01:15<00:05,  2.93s/trial, best loss: 555.6339008331669]                                                                                [17:18:58] WARNING: ../src/learner.cc:767:
[2025-07-13T17:18:58.779+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:18:58.782+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:00.348+0000] {subprocess.py:106} INFO -  93%|█████████▎| 28/30 [01:15<00:05,  2.93s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171858 at: http://mlflow:5000/#/experiments/1/runs/6681bcc50e424a929f828a37b61ecf75
[2025-07-13T17:19:00.350+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:00.352+0000] {subprocess.py:106} INFO -  93%|█████████▎| 28/30 [01:17<00:05,  2.93s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:19:00.353+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:00.701+0000] {subprocess.py:106} INFO -  93%|█████████▎| 28/30 [01:17<00:05,  2.93s/trial, best loss: 555.6339008331669] 97%|█████████▋| 29/30 [01:17<00:02,  2.65s/trial, best loss: 555.6339008331669]                                                                                [17:19:00] WARNING: ../src/learner.cc:767:
[2025-07-13T17:19:00.706+0000] {subprocess.py:106} INFO - Parameters: { "n_estimators" } are not used.
[2025-07-13T17:19:00.707+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:03.965+0000] {subprocess.py:106} INFO -  97%|█████████▋| 29/30 [01:17<00:02,  2.65s/trial, best loss: 555.6339008331669]                                                                                🏃 View run tune-20250713-171900 at: http://mlflow:5000/#/experiments/1/runs/91e0bd20d18c4d79bd360b88c3026bb8
[2025-07-13T17:19:03.966+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:03.967+0000] {subprocess.py:106} INFO -  97%|█████████▋| 29/30 [01:21<00:02,  2.65s/trial, best loss: 555.6339008331669]                                                                                🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:19:03.968+0000] {subprocess.py:106} INFO - 
[2025-07-13T17:19:04.426+0000] {subprocess.py:106} INFO -  97%|█████████▋| 29/30 [01:21<00:02,  2.65s/trial, best loss: 555.6339008331669]100%|██████████| 30/30 [01:21<00:00,  2.94s/trial, best loss: 555.6339008331669]100%|██████████| 30/30 [01:21<00:00,  2.71s/trial, best loss: 555.6339008331669]
[2025-07-13T17:19:04.427+0000] {subprocess.py:106} INFO - Best hyperparameters: {'learning_rate': 0.9176948444035711, 'max_depth': 6.0, 'min_child_weight': 1.0, 'n_estimators': 210.0, 'reg_alpha': 0.1915179446929954, 'reg_lambda': 0.5296081951243024}
[2025-07-13T17:19:04.428+0000] {subprocess.py:106} INFO - 🏃 View run log-best-params-20250713-171904 at: http://mlflow:5000/#/experiments/1/runs/ceb79231105a494d880f2aec5837639b
[2025-07-13T17:19:04.429+0000] {subprocess.py:106} INFO - 🧪 View experiment at: http://mlflow:5000/#/experiments/1
[2025-07-13T17:19:04.429+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T17:19:04.430+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 124, in <module>
[2025-07-13T17:19:04.431+0000] {subprocess.py:106} INFO -     tune(df, args.experiment_name, args.run_prefix, args.n_trials)
[2025-07-13T17:19:04.432+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/tune_model.py", line 99, in tune
[2025-07-13T17:19:04.435+0000] {subprocess.py:106} INFO -     mlflow.log_artifact(params_path, artifact_path="best_params")
[2025-07-13T17:19:04.436+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 1404, in log_artifact
[2025-07-13T17:19:04.437+0000] {subprocess.py:106} INFO -     MlflowClient().log_artifact(run_id, local_path, artifact_path)
[2025-07-13T17:19:04.438+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 2448, in log_artifact
[2025-07-13T17:19:04.440+0000] {subprocess.py:106} INFO -     self._tracking_client.log_artifact(run_id, local_path, artifact_path)
[2025-07-13T17:19:04.441+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 639, in log_artifact
[2025-07-13T17:19:04.442+0000] {subprocess.py:106} INFO -     artifact_repo.log_artifact(local_path, artifact_path)
[2025-07-13T17:19:04.443+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 45, in log_artifact
[2025-07-13T17:19:04.444+0000] {subprocess.py:106} INFO -     shutil.copy2(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
[2025-07-13T17:19:04.445+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 476, in copy2
[2025-07-13T17:19:04.446+0000] {subprocess.py:106} INFO -     copystat(src, dst, follow_symlinks=follow_symlinks)
[2025-07-13T17:19:04.446+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 384, in copystat
[2025-07-13T17:19:04.447+0000] {subprocess.py:106} INFO -     lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
[2025-07-13T17:19:04.448+0000] {subprocess.py:106} INFO - PermissionError: [Errno 1] Operation not permitted
[2025-07-13T17:19:05.080+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T17:19:05.120+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T17:19:05.132+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, run_id=scheduled__2025-07-12T00:00:00+00:00, execution_date=20250712T000000, start_date=20250713T171734, end_date=20250713T171905
[2025-07-13T17:19:05.204+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T17:19:05.206+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 95)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T17:19:05.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T17:19:05.331+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T17:19:05.340+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
