[2025-07-15T01:22:11.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-15T01:22:11.152+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-07-14T00:00:00+00:00 [queued]>
[2025-07-15T01:22:11.184+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-07-14T00:00:00+00:00 [queued]>
[2025-07-15T01:22:11.186+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-15T01:22:11.266+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-07-14 00:00:00+00:00
[2025-07-15T01:22:11.299+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2082) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-15T01:22:11.290+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'scheduled__2025-07-14T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmph7ls_cvp']
[2025-07-15T01:22:11.309+0000] {standard_task_runner.py:72} INFO - Started process 2090 to run task
[2025-07-15T01:22:11.335+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask download_and_ingest
[2025-07-15T01:22:11.538+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-15T01:22:11.968+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest scheduled__2025-07-14T00:00:00+00:00 [running]> on host d84888688479
[2025-07-15T01:22:11.982+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-15T01:22:12.475+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='download_and_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-14T00:00:00+00:00'
[2025-07-15T01:22:12.477+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-15T01:22:12.556+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-15T01:22:12.558+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/download_ingest.py                 --year 2022                 --month 7                 --start_day 30                 --end_day 1                 --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --table_name raw_turnstile_data\n        ']
[2025-07-15T01:22:12.596+0000] {subprocess.py:99} INFO - Output:
[2025-07-15T01:22:20.785+0000] {subprocess.py:106} INFO - [INFO] Fetching data for dates: []
[2025-07-15T01:22:20.786+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-15T01:22:20.788+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 58, in <module>
[2025-07-15T01:22:20.792+0000] {subprocess.py:106} INFO -     download_and_ingest(**vars(args))
[2025-07-15T01:22:20.793+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/download_ingest.py", line 27, in download_and_ingest
[2025-07-15T01:22:20.796+0000] {subprocess.py:106} INFO -     df_raw = pd.concat(dfs, ignore_index=True)
[2025-07-15T01:22:20.797+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-15T01:22:20.798+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
[2025-07-15T01:22:20.799+0000] {subprocess.py:106} INFO -     op = _Concatenator(
[2025-07-15T01:22:20.800+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^
[2025-07-15T01:22:20.801+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
[2025-07-15T01:22:20.802+0000] {subprocess.py:106} INFO -     objs, keys = self._clean_keys_and_objs(objs, keys)
[2025-07-15T01:22:20.806+0000] {subprocess.py:106} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-15T01:22:20.809+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
[2025-07-15T01:22:20.810+0000] {subprocess.py:106} INFO -     raise ValueError("No objects to concatenate")
[2025-07-15T01:22:20.811+0000] {subprocess.py:106} INFO - ValueError: No objects to concatenate
[2025-07-15T01:22:21.068+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-15T01:22:21.096+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-15T01:22:21.104+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, run_id=scheduled__2025-07-14T00:00:00+00:00, execution_date=20250714T000000, start_date=20250715T012211, end_date=20250715T012221
[2025-07-15T01:22:21.155+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-15T01:22:21.157+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task download_and_ingest (Bash command failed. The command returned a non-zero exit code 1.; 2090)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-15T01:22:21.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-15T01:22:21.277+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T01:22:21.290+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
