[2025-07-06T15:54:10.689+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509
[2025-07-06T15:54:10.692+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest'
[2025-07-06T15:54:10.847+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509
[2025-07-06T15:54:10.850+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest'
[2025-07-06T15:54:10.976+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-06T15:53:43+00:00 [queued]>
[2025-07-06T15:54:11.008+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-06T15:53:43+00:00 [queued]>
[2025-07-06T15:54:11.010+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-06T15:54:11.056+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_and_ingest> on 2025-07-06 15:53:43+00:00
[2025-07-06T15:54:11.092+0000] {standard_task_runner.py:57} INFO - Started process 40 to run task
[2025-07-06T15:54:11.141+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'download_and_ingest', 'manual__2025-07-06T15:53:43+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpovq9jqiu']
[2025-07-06T15:54:11.144+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask download_and_ingest
[2025-07-06T15:54:11.202+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T15:54:11.472+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509
[2025-07-06T15:54:11.483+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=manual__2025-07-06T15:53:43+00:00/task_id=download_and_ingest'
[2025-07-06T15:54:11.497+0000] {task_command.py:416} INFO - Running <TaskInstance: turnstile_ml_pipeline.download_and_ingest manual__2025-07-06T15:53:43+00:00 [running]> on host 0e981b5735bc
[2025-07-06T15:54:11.823+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'download_and_ingest', field 'bash_command'. Template: '\n            python /opt/***/pipeline/download_ingest.py                 --year {{ params.year }}                 --month {{ params.month }}                 --start_day {{ params.start_day }}                 --end_day {{ params.end_day }}                 --user {{ var.value.PG_USER }}                 --password {{ var.value.PG_PASSWORD }}                 --host {{ var.value.PG_HOST }}                 --port {{ var.value.PG_PORT }}                 --db_name {{ var.value.PG_DB_NAME }}                 --table_name raw_turnstile_data\n        '
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 22, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 104, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable PG_USER does not exist'
[2025-07-06T15:54:11.830+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 22, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 104, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable PG_USER does not exist'
[2025-07-06T15:54:11.852+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=download_and_ingest, execution_date=20250706T155343, start_date=20250706T155410, end_date=20250706T155411
[2025-07-06T15:54:11.899+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task download_and_ingest ('Variable PG_USER does not exist'; 40)
[2025-07-06T15:54:11.953+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-06T15:54:12.017+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
